name: Daily benchmark
on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  benchmark:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x

    - name: Setup dependencies
      run: |
        sudo add-apt-repository ppa:cowsql/main -y
        sudo apt update
        sudo apt install -y libsqlite3-dev libuv1-dev liblz4-dev libraft-dev libcowsql-dev

    - name: Build & Benchmark
      env:
        CGO_LDFLAGS_ALLOW: "-Wl,-z,now"
        GO_DQLITE_MULTITHREAD: 1
      run: |
        go get -t -tags libsqlite3 ./...
        go install -tags libsqlite3 github.com/cowsql/go-cowsql/cmd/cowsql-benchmark
        cowsql-benchmark --db 127.0.0.1:9001 --duration 3600 --driver --cluster 127.0.0.1:9001,127.0.0.1:9002,127.0.0.1:9003 --workload kvreadwrite &
        masterpid=$!
        cowsql-benchmark --db 127.0.0.1:9002 --join 127.0.0.1:9001 &
        cowsql-benchmark --db 127.0.0.1:9003 --join 127.0.0.1:9001 &
        wait $masterpid
        echo "Write results:"
        head -n 5 /tmp/cowsql-benchmark/127.0.0.1:9001/results/0-exec-*

        echo ""
        echo "Read results:"
        head -n 5 /tmp/cowsql-benchmark/127.0.0.1:9001/results/0-query-*

    - uses: actions/upload-artifact@v4
      with:
        name: cowsql-daily-benchmark
        path: /tmp/cowsql-benchmark/127.0.0.1:9001/results/*
